{% set name = "statflow" %}
{% set version = "3.5.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=68.0
    - wheel
  run:
    - python >=3.10
    - pip
    - numpy >=1.21.0,<2.0.0
    - pandas >=1.3.0,<2.0.0
    # Add other dependencies as needed

test:
  imports:
    - statflow
  commands:
    - python -c "import statflow; print(statflow.__version__)"

about:
  home: https://github.com/EusDancerDev/statflow
  license: MIT
  license_file: LICENSE
  summary: Python package statflow
  doc_url: https://github.com/EusDancerDev/statflow#readme
  dev_url: https://github.com/EusDancerDev/statflow.git

extra:
  recipe-maintainers:
    - EusDancerDev
